### ISSUE TITLE
Chaning docs version should put you at the same page if exists at the other version

### ISSUE THREAD

**Issue by ikfir** [PoweredByApartium/cocoa-beans#101]
For example
![image](https://github.com/PoweredByApartium/cocoa-beans/assets/6349137/af72c479-b7c7-4c22-9f97-bb1cbd8033dd)
If we change version to `v182.0.3.test`
![image](https://github.com/PoweredByApartium/cocoa-beans/assets/6349137/b6902a87-6be9-4c03-b531-c657b9020a5e)
It send us back to home page and not 🔐 Advanced reusable parsers﻿
![image](https://github.com/PoweredByApartium/cocoa-beans/assets/6349137/91dcdd88-1cc9-4dae-90c6-f9de390b9d22)

### Here is what it should look like
![image](https://github.com/PoweredByApartium/cocoa-beans/assets/6349137/9379be37-3a2a-4ee2-bcef-283e456721f3)
![image](https://github.com/PoweredByApartium/cocoa-beans/assets/6349137/c1549727-31d0-49ed-96b5-2e609a4105b2)
no home page
![image](https://github.com/PoweredByApartium/cocoa-beans/assets/6349137/10dd93a0-6df0-4eb4-839f-6e5ec8c4ea89)

**Comment by liorsl** [comment]
Fixed
