### ISSUE TITLE
Command System Add parameter name for argument mapping 

### ISSUE THREAD

**Issue by ikfir** [PoweredByApartium/cocoa-beans#105]
For example
```java
@SubCommand("<int=amount> <int=id>")
public void give(@Param("id") int id, Sender sender, @Param("amount") int amount) {
  // Do something
}
```
This could be useful in some cases to just save you time and will be easier to understand where each parameter go
also it can still be use in the old way as queue

and even combine for example
```java
@SubCommand("<int=amount> <int> <int=id>")
public void give(@Param("id") int id, Sender sender, int magicValue, @Param("amount") int amount) {
  // Do something
}
// Or even
@SubCommand("<int=amount> <int> <int=id>")
public void give(int magicValue, @Param("id") int id, Sender sender, @Param("amount") int amount) {
  // Do something
}
```

It will know base on that isn't tagged but we can do another thing as well
```java
@SubCommand("<int=amount> <int> <int=id>")
public void give(int magicValue, int idNum, Sender sender, @Param("amount") int amount) {
  // Do something
}
```

**Comment by liorsl** [comment]
Alternatives for =:

- <int as amount>
- <amount int>
- <int amount>
- <amount: int>

**Comment by IdanKoblik** [comment]
~@:

**Comment by IdanKoblik** [comment]
<{amount}:int>
<{name}:String>

**Comment by ikfir** [comment]
Vote for what you like the most

:heart: `<int as amount>`
:rocket: `<amount: int>`
:tada: `<int=amount>`

**Comment by IdanKoblik** [comment]
All of them available for use

**Comment by ikfir** [comment]
@IdanKoblik 
> All of them available for use

That would be a bad idea for couple reason
1. Implemention will be harder for parsing but is do able
2. Can make code not consistent
     For example
```java
@SubCommand("<int as amount> <cost: double> <string=name> <int>")
```
