### ISSUE TITLE
EnchantGlow multi version support

### ISSUE THREAD

**Issue by ofirtim** [PoweredByApartium/cocoa-beans#137]
I am writing it as I have no idea how to implement such a thing.

The current Enchant glow is working as a normal Unsafe Enchantment, and this stresses me a little bit around using EnchantGlow.
What I think should be done to fix this is either create a none Enchantment filler method, or see a higher level implementation against 1.8 old-school ID's to 1.13 flattened Keyspaces.

**Comment by ofirtim** [comment]
@ikfir @liorsl This has yet to be patched, and it shouldn't take longer than the average 50-60 minute work time.
`Caused by: java.lang.RuntimeException: Unsupported server version MinecraftVersion[major=1, update=18, minor=2]`

**Comment by liorsl** [comment]
Too shamen, see #147
