### ISSUE TITLE
Make way to make parser as annoation more dynamic 

### ISSUE THREAD

**Issue by ikfir** [PoweredByApartium/cocoa-beans#143]
For today we have 2 parsers `WithParser` & `SourceParser`

I would want to just to have factory to take care of it like we do it requirement factory like we have `CommandRequirementType`
```java
@CommandParser(SourceParserFactory.class)
@Target({ElementType.METHOD})
@Retention(RetentionPolicy.RUNTIME)
public @interface SourceParser {
   // etc...
}
```

**Comment by liorsl** [comment]
Cool idea, lets do it
