### ISSUE TITLE
Command System

### ISSUE THREAD

**Issue by ikfir** [PoweredByApartium/cocoa-beans#20]

**Comment by liorsl** [comment]
Some important points we talked about:
- Platform neutral code (IE allow to work with CLI / Bungeecord / Velocity etc)
- Have a command context class
- Ensure stability using unit tests

**Comment by liorsl** [comment]
- [ ] Base class for commands
- [ ] Argument parsing hints
- [ ] Serializers receive argument param context and return the context that they've used to serialize, if successful (can be validations on min max numbers or parsing settings like array start and end indicators)
- [ ] Built in serializers (both java types and platform dependent types)
- [ ] Return CommandResult from whole command, each platform handles differently
