### ISSUE TITLE
[spigot] ItemBuilder lore improvements

### ISSUE THREAD

**Issue by ofirtim** [PoweredByApartium/cocoa-beans#206]
Right now the only options in ItemBuilder are `setLore(List<Component>)`, I would like you to implement an option for single-component building.

**Comment by ofirtim** [comment]
Update: I am gonna be creating an additional branch for this, also I think the lore editing needs a little addition.
 with permission of course, I would like to add a few options to the lore system @liorsl

**Comment by liorsl** [comment]
What would you like to add?

**Comment by ofirtim** [comment]
> What would you like to add?

Direct approach to add lore lines with components as well.
And I think this is a good time to add my lore editor and connect it with this system.

**Comment by liorsl** [comment]
Your LoreEditor could be a nice addition to CocoaBeans but I think should have its own PR since it will require more work.
You are good to go on both

**Comment by liorsl** [comment]
Great, but as a reminder you will need to make the system support two modes:
- With native Kyori, so you have ItemMeta#lore methods
- Without native Kyori, so you will have to translate the lore to legacy

I am not sure if this is done in the existing setLore code, but it should be there as well if we are already working on that

**Comment by ofirtim** [comment]
> Great, but as a reminder you will need to make the system support two modes:
> 
> * With native Kyori, so you have ItemMeta#lore methods
> * Without native Kyori, so you will have to translate the lore to legacy
> 
> I am not sure if this is done in the existing setLore code, but it should be there as well if we are already working on that

There is a part of it working.
Also, I stumbled upon a weird code that was set in the MetaData system.
apparently, @ikfir used a wrong approach to the MetaData of item lore, as he did not notice you could not add lore lines to existing lore in MetaData class, please allow me to edit Kfir's code and fix this issue immediately

**Comment by liorsl** [comment]
Go ahead
